# This is a basic workflow to help you get started with Actions

name: Andre 


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request: [MAIN]
    branches: [ PULL REQUEST ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Teach me to code please please I'm cluesless workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: me into a coder.
    # The type of runner that the job will run on
    runs-on: nothing but redbull⅚

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:guide me in the world of coding, help me learn a skill I can use in life
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkdrizzy

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |network and work

          echo Add other actions to build,
          echo test, and deploy your project.
